### ISSUE TITLE
Pipeline hangs

### ISSUE THREAD

**Issue by FHusko** [SWIFTSIM/morpholopy#7]
When I try to run the pipeline, it appears to hang after the following output:
```
[      0.51] [PID159805] Computing properties for 66 galaxies using 66 parallel processes...
[     19.70] [PID164381] [galaxy 50] Galaxy 50: stellar mass: 2.16e+10
[     19.72] [PID159942] [galaxy 48] Galaxy 48: stellar mass: 2.11e+10
[     19.76] [PID164920] [galaxy 56] Galaxy 56: stellar mass: 1.83e+10
[     19.76] [PID159975] [galaxy 21] Galaxy 21: stellar mass: 7.61e+10
[     19.80] [PID164091] [galaxy 39] Galaxy 39: stellar mass: 2.09e+10
[     19.89] [PID159969] [galaxy 25] Galaxy 25: stellar mass: 2.05e+10
[     19.90] [PID164917] [galaxy 68] Galaxy 68: stellar mass: 2.22e+10
[     19.92] [PID159953] [galaxy 19] Galaxy 19: stellar mass: 2.67e+10
[     19.93] [PID160051] [galaxy 30] Galaxy 30: stellar mass: 4.88e+10
[     19.99] [PID159972] [galaxy 40] Galaxy 40: stellar mass: 1.34e+10
[     20.02] [PID164929] [galaxy 64] Galaxy 64: stellar mass: 1.11e+10
[     20.03] [PID159961] [galaxy 36] Galaxy 36: stellar mass: 3.44e+10
[     20.06] [PID159987] [galaxy 8] Galaxy 8: stellar mass: 6.23e+10
[     20.08] [PID159950] [galaxy 33] Galaxy 33: stellar mass: 4.01e+10
[     20.09] [PID159968] [galaxy 5] Galaxy 5: stellar mass: 1.18e+11
[     20.10] [PID159944] [galaxy 35] Galaxy 35: stellar mass: 2.84e+10
[     20.10] [PID159951] [galaxy 42] Galaxy 42: stellar mass: 1.70e+10
[     20.11] [PID160047] [galaxy 20] Galaxy 20: stellar mass: 6.43e+10
[     20.38] [PID160009] [galaxy 10] Galaxy 10: stellar mass: 6.66e+10
[     23.18] [PID159984] [galaxy 41] Galaxy 41: stellar mass: 3.62e+10
[     23.32] [PID160151] [galaxy 32] Galaxy 32: stellar mass: 1.04e+10
[     23.43] [PID164380] [galaxy 53] Galaxy 53: stellar mass: 3.19e+10
[     23.49] [PID159977] [galaxy 26] Galaxy 26: stellar mass: 5.74e+10
[     23.50] [PID159979] [galaxy 24] Galaxy 24: stellar mass: 1.98e+10
[     23.53] [PID159946] [galaxy 44] Galaxy 44: stellar mass: 1.62e+10
[     23.54] [PID159980] [galaxy 7] Galaxy 7: stellar mass: 4.59e+10
[     23.58] [PID159965] [galaxy 34] Galaxy 34: stellar mass: 2.81e+10
[     23.63] [PID159964] [galaxy 1] Galaxy 1: stellar mass: 6.95e+10
[     26.54] [PID164381] [galaxy 70] Galaxy 70: stellar mass: 1.70e+10
[     27.32] [PID159981] [galaxy 37] Galaxy 37: stellar mass: 1.95e+10
[     27.64] [PID159971] [galaxy 0] Galaxy 0: stellar mass: 1.51e+11
```

It throws one error message after the above output:
```
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/cosma/local/Python/3.10.1/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/cosma/local/Python/3.10.1/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/cosma/local/Python/3.10.1/lib/python3.10/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/cosma/local/Python/3.10.1/lib/python3.10/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: UnitConversionError.__init__() missing 4 required positional arguments: 'unit1', 'dimension1', 'unit2', and 'dimension2'
```
after which it hangs indefinitely, without writing out any plots or a data file.

This is how I use the pipeline:
```
module purge

module load python/3.10.1 gnu_comp/11.1.0 openmpi/4.1.1

./build_env/bin/python3 morphology-pipeline \
  -C /cosma/home/durham/dc-husk1/morpholopy/colibre_config \
  -i /cosma8/data/dp004/dc-husk1/SWIFT/COLIBRE/runs3_Leiden_tests/LR25_fid_U160 \
  -s colibre_0001.hdf5 \
  -c haloes_0001.properties.0 \
  -o /cosma/home/durham/dc-husk1/Cosmo_boxes/COLIBRE_25_lowres/morphology \
  -n LR25_fid_U160
```
I use a local python environment as recommended on the morphology github, which I build using:
```
> python3 -m venv build_env
> ./build_env/bin/pip install --upgrade pip
> ./build_env/bin/pip install -r requirements.txt
```
with `mpi4py` also added into `requirements.txt`

**Comment by robjmcgibbon** [comment]
I'm going to close this for now given that this was > 1 year ago, so it's probably hard to reproduce. Let's see if any of us get this issue with the updated version
